### ISSUE TITLE
SDK user can modify location collection frequency, accuracy and transmission frequency via API

### ISSUE THREAD

**Issue by simonatsafegraph** [OpenLocate/openlocate-android#27]
This means that when location data is ingested, that API can return a config that changes the parameters for location collection. The app will now use the returned config

**Comment by davidargylethacker** [comment]
In the meantime while this is note configurable it would nice if these values were documented somewhere. I'm curious about the frequency of the location collection, and the submission via the API. 

Wouldn't mind pitching in to help make this a real feature too. Where is this setup in code right now?

**Comment by kurabi** [comment]
@davidargylethacker The README has been updated as part of PR #65 to show how you can configure this.
