### ISSUE TITLE
Add custom property support for Map<String, String>

### ISSUE THREAD

**Issue by fritzrichter** [OpenLocate/openlocate-android#59]
It would be nice to let the developer add custom key/value pairs, which he wants to transmit as well via the JSON payload as Map<String,String> to provide a flexible and generic way of enhancing the payload which is sent to the configured endpoint. See [iOS Ticket as well](https://github.com/OpenLocate/openlocate-ios/issues/65)

**Comment by kurabi** [comment]
Would these value be something passed in on initialization? or changeable at any time?

**Comment by kurabi** [comment]
@fritzrichter It should be noted that you can currently pass in custom properties in the `Configuration` class via the `setHeaders(...)` method. Let me know for some reason that does not fit your needs.
