### ISSUE TITLE
Testing OpenLocate features while in development

### ISSUE THREAD

**Issue by davidargylethacker** [OpenLocate/openlocate-android#67]
Is there a way to verify that OpenLocate is working and tracking location data without having to send data over http posts? It would be nice to check that the library is tracking location data at the frequency I expect and that events are getting inserted into the database correctly before I post anything. 

Also I wasn't sure if this question belonged here or not, I've also created this post on StackOverflow https://stackoverflow.com/questions/47800769/development-logs-and-testing-for-openlocate

**Comment by simonatsafegraph** [comment]
Hi David - I think the simplest way is just to inspect the data in the local database. Data is saved there before it's transmitted in batches to the endpoints specified in the configuration block.

Let us know if that works for you!
