### ISSUE TITLE
Please using ContextCompat.startForegroundService to avoid crash under Android O

### ISSUE THREAD

**Issue by tangjingyuan** [OpenLocate/openlocate-android#70]
This [code snippet](https://github.com/OpenLocate/openlocate-android/blob/e58d3b54ae3217e111963c38e071747789c15416/openlocate/src/main/java/com/openlocate/android/core/OpenLocate.java#L605) will cause crash under Android O.

According to [the doc of Background execution limits](https://developer.android.com/about/versions/oreo/android-8.0-changes.html#atap), startService will throws an **IllegalStateException** when app isn't permitted to create background services.

**Comment by kurabi** [comment]
@tangjingyuan Are you saying the app crashes for you because of this?

I have tried this on Android O, and it does not crash nor do we violate this API.

**Comment by tangjingyuan** [comment]
@kurabi please see the following pic. So many crashes caused by startService.... 

![image](https://user-images.githubusercontent.com/12523498/35547707-9c227bee-05b5-11e8-89e5-3c5ecff104b9.png)

**Comment by kurabi** [comment]
@tangjingyuan As per the doc:

> The new Context.startForegroundService() method starts a foreground service. The system allows apps to call Context.startForegroundService() even while the app is in the background. However, the app must call that service's startForeground() method within five seconds after the service is created.

The code snippet that starts a foreground service:
https://github.com/OpenLocate/openlocate-android/blob/90f62ae6b2c359818cde781d796b1e5086a4b9b6/openlocate/src/main/java/com/openlocate/android/core/LocationServiceHelper.java#L347

Are you using a modified version of the project?

**Comment by kurabi** [comment]
Also, what is your targetSdkVersion?

**Comment by tangjingyuan** [comment]
@kurabi The targetSdkVersion  is 26 and I imported OpenLocate according to your wiki:

> repositories {
    maven {
        url "https://s3-us-west-2.amazonaws.com/openlocate-android/"
    }
}
compile 'com.openlocate:openlocate:1.+'

I reviewed OpenLocate.java and I found startService triggered after I called OpenLocate.getInstance().startTracking(Activity).

The startService will be called after permissions check in [OpenLocate#onFetchAdvertisingInfo](https://github.com/OpenLocate/openlocate-android/blob/e58d3b54ae3217e111963c38e071747789c15416/openlocate/src/main/java/com/openlocate/android/core/OpenLocate.java#L593)

**Comment by kurabi** [comment]
Sample app and sdk have target version of 25. So this crash is likely because of that. Use 25 in meantime if possible.

**Comment by simonatsafegraph** [comment]
@tangjingyuan -- closing this for now. We will work on a way to support target version 26+ in longer term.

**Comment by paulpv** [comment]
Also see https://issuetracker.google.com/issues/76112072
