### ISSUE TITLE
Is it possible to detect stops with this?

### ISSUE THREAD

**Issue by MohitKumar1991** [OpenLocate/openlocate-android#79]

**Comment by simonatsafegraph** [comment]
Hi Mohit -- OpenLocate on Android simply polls for location data (via Google Play Services) at a given interval (e.g. 20, 30 minutes). Inferring that the user has "stopped" would depend on your post-processing of data.

Note that OpenLocate on iOS does use [CLVisits](https://developer.apple.com/documentation/corelocation/clvisit) -- a feature built into iOS that automatically generates location records when users have stopped at a place. CLVisits itself determines what constitutes a visit.

**Comment by MohitKumar1991** [comment]
Thanks a lot for the response. 

Correct me if I am wrong, but I think it is possible to detect the speed from the Android APIs. The reason I wanted to detect stops on the client side is so that I can set variable intervals for when the person is idle and when he is moving. I think that is a really must feature. I am happy to work on it if you can guide me on how that should happen according to you.

**Comment by simonatsafegraph** [comment]
Hi Mohit -- yes, that's a good point. You can indeed collect user's speed. check this: https://github.com/OpenLocate/openlocate-android#fields-collected-by-the-sdk. Does that do what you need? Or, what were you envisioning? Would be great to have you helping out on the project!
