### ISSUE TITLE
Transmission interval & interval to get data

### ISSUE THREAD

**Issue by Iliasvw** [OpenLocate/openlocate-android#83]
Hello

Currently trying to make a project with the OpenLocate SDK. When I try to set the LocationInterval and TransmissionInterval to something like 10 seconds, new updates are getting pushed into the database every minute and not every 10 seconds & data is being pushed to the server every 5 minutes. How is this possible?

The location service also shows me a log: 
LocationService W/OkHttpClient: A connection to URL was leaked. Did you forget to close a response body?

Maybe a quick fix?

Thanks in advance
Ilias

**Comment by kurabi** [comment]
In the background, the OS throttles how fast location and batch upload occurs. So it’s unlikely to meet the very low rates you have set. Consider using a foreground service in your app so that the OS can respect those values. 

Regarding warning, are you using the Example app included? I will take a look.

**Comment by Iliasvw** [comment]
The warning is in my own project and not the example project.

For those low rates, I'm currently using an IntentService to repeatingly ask the current location information. Is this what you mean?

**Comment by kurabi** [comment]
A Foreground Service so the system can allow the service to run constantly:
https://developer.android.com/guide/components/services.html#Foreground

**Comment by Iliasvw** [comment]
This is what I am doing right now. In the service, I create a Runnable in which I repeatedly call the getCurrentLocation method. Is this what you mean?

**Comment by kurabi** [comment]
Start the service as a foreground service as per the link mentioned.

**Comment by kurabi** [comment]
> Start a foreground service of the LocationService

Correct. Try that and see if it works. You can quickly try this by running the example app and modifying the SDK.

**Comment by kurabi** [comment]
Regarding the warning "W/OkHttpClient: ..." Only the Example app uses `OkHttpClient`, the SDK does not. Are you using `OkHttpClient`?

**Comment by Iliasvw** [comment]
Regarding the warning, I'm not using the OkHttpClient. 

In my application I have a service which repeatedly calls the getCurrentLocation method and display the data on the screen.

The user has the possibility to fill in the interval to track data and send data to the server (transmission interval).

When I look into the SDK, a foreground service is already started of the LocationService, so why start a second one? If I start a new one, the problem is still the same.

**Comment by kurabi** [comment]
> Regarding the warning, I'm not using the OkHttpClient.

The SDK does not use it either, please check your dependencies.

OpenLocate isn't really designed for really fast fetch and transmit interval as that has a big battery impact.

**Comment by Iliasvw** [comment]
Problem seems to be with Android 8. As your targetSdk is 25, and the latest version is 27, that causes the problem. It still doesn't log as frequently as I want, but I think it has to do with the way the foreground service is started, as Orea requires another way of building the notification and start de foreground service.
