### ISSUE TITLE
Untie library from sample app

### ISSUE THREAD

**Issue by Nikituh** [OpenLocate/openlocate-android#86]
The sample app is a bit bloated (I don't want tons of third-party dependencies) so I built one from scratch, just adding the published version to dependencies. 

Now, I need to make a few changes to the SDK, among other things, https://github.com/OpenLocate/openlocate-android/issues/85 and the option to send data manually (as in the iOS application), however, I am having a hard time building the local library, as the app is a dependency of it.

Adding as local library:
![screen shot 2018-05-16 at 13 45 25](https://user-images.githubusercontent.com/8685359/40112653-69558f8c-590f-11e8-87d1-21ca370af034.png)

Result:
![screen shot 2018-05-16 at 13 45 49](https://user-images.githubusercontent.com/8685359/40112680-796014b0-590f-11e8-81ab-a073aab89f54.png)

I don't want to build the app that does not build out of the box. I want to build OpenLocate library.

* The library should be a separate project
* Sample apps should use released versions
* The working/debug app should be under .gitignore, or at least separate from sample projects

**Comment by kurabi** [comment]
PRs are welcome. But the project should have a sample app for developers to try the SDK with.
