### ISSUE TITLE
Support API level 26 or higher

### ISSUE THREAD

**Issue by steven-ai** [OpenLocate/openlocate-android#89]
When I use OpenLocate on my smartphone (Android 8.0, API version 26), I get a sticky notification.
This is probably due to the changes by Android: https://developer.android.com/about/versions/oreo/background-location-limits

Will this be solved so that OpenLocate can be used on Android 8 without sticky notification?

**Comment by kurabi** [comment]
We are working on support for a non-foreground service solution. Feel free to look at the `android_o` branch. It is pretty much complete and just needs testing.

**Comment by kenneth-g-flux** [comment]
Hi, I was just looking through the `android_o_support`-branch and I'm seeing usage of `com.google.android.gms.gcm.GcmNetworkManager` in `OpenLocateHelper`. If I'm not mistaking GCM server and client APIs are deprecated (https://developers.google.com/cloud-messaging/network-manager) and will be removed as soon as April 2019. Is there a roadmap for migrating that branch to FCM?

**Comment by kurabi** [comment]
This was just deprecated like a month ago, but yes we do plan on updating any deprecated APIs in the future.
