### ISSUE TITLE
getCurrentLocation method not found

### ISSUE THREAD

**Issue by DeveloperMohamedHelmy** [OpenLocate/openlocate-android#98]
I can't find this method in the sdk version 2.0.0, is any alternative method or any callback to get user location?
is this method fires if location recorded on the database ? if not is there any solution to know when the OpenLocate sdk record or save a location update?

this is the method as in documentation :-

Using user's location to query 3rd party Places APIs
To use user's current location, obtain the location by calling getCurrentLocation method on OpenLocate. Get the instance by calling getInstance. Use the fields collected by SDK to send to 3rd party APIs.

For example, to obtain user location:
OpenLocate openLocate = OpenLocate.getInstance();

openLocate.getCurrentLocation(new OpenLocateLocationCallback() {
    @Override
    public void onLocationFetch(OpenLocateLocation location) {
        //Use location object to obtain fields and pass it to 3rd Party API
    }

    @Override
    public void onError(Error error) {
       //error
    }
});

**Comment by kurabi** [comment]
There is not, this Api is not supported in v2.0.0 for technical reasons.
